### PR TITLE
Translation into Spanish

### PR DESCRIPTION
**Pull request by nvdaes**
- delete sentenc
- Translate into Spanish

### CODE REVIEW

**Comment by nvdaes** [comment]
@NSoiffer Please review this when you want.

**Comment by NSoiffer** [comment]
You mentioned in email that you wanted to remove articles (the/a) from the translation to avoid problems with gender. I think most of the ones that are in the translation are ok because they are followed by a known word so you can get the gender right. However, there are the ones for raising to a power. They use "a la". Is there a potential gender problem when the exponent is a number (which is spoken as an ordinal such as cuarto)?

Also, I see an inconsistency: the rule for sqrt doesn't use "the" but the rule for root does use it. Is that is intentional? 

Finally (and I hate to mention it because it means more work): did you translate the files in SharedRules? Those need to be translated. Maybe you just forgot to commit or push them?

**Comment by nvdaes** [comment]
> They use "a la". Is there a potential gender problem when the exponent is a number (which is spoken as an ordinal such as cuarto)?

In those cases, the ordinal in spanish should be female

> the rule for sqrt doesn't use "the" but the rule for root does use it. Is that is intentional?

No, it's probably amistake. I'll check it.


> did you translate the files in SharedRules? Those need to be translated.

Oh sorry. I didn't know if I should translate this. I'll do probably in about 15 hours.

**Comment by NSoiffer** [comment]
Apologies if I didn't mention it. I thought it got mentioned because you asked the question about "negative b" in the quadratic formula and I said you needed to change a rule in `SharedRules/general.yaml`. I apologize for not being clearer about this. There are a lot of repetitions in the files, so some global search/replace might speed things up.

Also, there are a couple of rules that are "ot" (omit text if there is a repetition -- avoids "the the" in some cases) and "ct" (concatenate text). These need translation. The later use is for adding an "s" to some words. Here's the usage:
```
  - test:
    - if: "self::m:cases"
      then: [{t: "case"}]
    - else_if: "self::m:equations"
      then: [{t: "equation"}]
      else: [{t: "line"}]
  - test:
    - if: "count(*) > 1"
      then: [{ct: "s"}] # plural
```

I don't think this works for the Spanish, so you probably need something like what is below, where you change the English to Spanish (there may be a typo -- I haven't tested this):
```
  - test:
    - if: "self::m:cases"
      then: [t: "IfThenElse(count(*)-=1, 'case', 'cases']"]
    - else_if: "self::m:equations"
      then: [{t: "IfThenElse(count(*)-=1, 'equation', 'equations']"]
      else: [{t: "IfThenElse(count(*)-=1, 'line', 'lines']"}]
```

**Comment by nvdaes** [comment]
I'll continue with this work in the next days. It may take some time.
Notes:

- The words scripts and pre or postscripts may have a right way to be translated, but I don't know and I don't find it.
- Box has been translated by "caja", but "cuadro" maybe appropriate too.

Al maybe improved if one day we discovered some mistake or a way to enhance any translation, though I'm searching in sources which I consider reliable when needed.

**Comment by NSoiffer** [comment]
> The words scripts and pre or postscripts may have a right way to be translated, but I don't know and I don't find it.

It is rather awkward English also, so don't feel bad about it. It probably won't come up very often.

**Comment by nvdaes** [comment]
Hi @NSoiffer , please feel free to review/merge this translation, sent today by my friend María. Let us know if something needs to be fixed.

**Comment by nvdaes** [comment]
Hi Neil: María has translated this having great knowledge of English (she is specialized in this language at University). I looked just the quadratic equation. I can test with Rust in the next days. Please wait until the next weekend to give me time to perform tests.Enviado desde mi iPhoneEl 26 jun 2023, a las 20:43, NSoiffer ***@***.***> escribió:﻿
I'm still looking through files, but so far everything looks good (although I can't comment on the translations specifically). I'm using them to fine turn English phrases for auto translations (still far from perfect). Did you or Maria listen to some expressions in Spanish in NVDA to make sure there are no syntax or other big issues that interfere with it working?
Also, are you able to build (using Rust) and run MathCAT tests on your system? The next step is to add at least a few tests so that future changes/updates can be at least sanity checked that they still run. If you can't run the tests, after I approve the changes, I'll send you a few "failures" (they will fail because the expected test result is in English). I'll ask you to verify that the Spanish is correct and change the files and then I'll commit those. I'll start with two files, but the more you or Maria are willing to verify, the more likely the Spanish remains correct.

**Comment by nvdaes** [comment]
I've installed Rust though seems that the installer is not very
accessible when it's started, so I have pressed Enter and tab to try
to install it.
Now I'm getting the following error when trying to run the cargo test
en command:

error: the 'cargo.exe' binary, normally provided by the 'cargo'
component, is not applicable to the 'stable-x86_64-pc-windows-msvc'
toolchain


Should I install the 32 bits version? I've installed both since the
first time, when trying to install the 64 bits, NVDA told me that I
was in the default terminal and then I thought that this was not
working properly. Later I realised that the installer was not very
accessible.
Thanks for your help.

2023-06-26 21:16 GMT+02:00, Noelia Ruiz Martínez ***@***.***>:

**Comment by nvdaes** [comment]
I used the mentioned page, also provided in your documentation. I've
reinstalled Rust and perhaps I wasn't enough patient and didn't wait
enough to hear messages provided by NVDA. Now Rust seems to be
installed, but I'm requested to run a command to add cargo component,
but I'm getting the following error:

info: latest update on 2023-06-01, rust version 1.70.0 (90c541806
2023-05-31)
error: Missing manifest in toolchain 'stable-x86_64-pc-windows-msvc'

Thanks for your help.

2023-06-27 19:08 GMT+02:00, NSoiffer ***@***.***>:

**Review by NSoiffer — APPROVED** [review]
Look good. Thanks!

**Comment by nvdaes** [comment]
Thank you. Looking forward to see this in the NVDA add-on, maybe a beta version... CheersEnviado desde mi iPhoneEl 28 jun 2023, a las 21:29, NSoiffer ***@***.***> escribió:﻿
@NSoiffer approved this pull request.

Look good. Thanks!

**Comment by NSoiffer** [comment]
I'm on my way to the (US) National Federation of the blind convention. I think I will have some free time on Tuesday or Wednesday to do a build that incorporates your Spanish translation. I'd feel more confident if there at least a few tests so really big problems (e.g., syntax errors in the YAML files) get caught.

**Comment by nvdaes** [comment]
Thanks. A member of my NVDA spanish mailing list is helping to include some tests for this. I'll include a link to this PR for him on ntion!the [relevant topic](https://nvdaes.groups.io/g/lista/topic/99016398). Please wait for his reply if you want.
Enjoy the conve

**Comment by nvdaes** [comment]
@NSoiffer My fellow on the Spanish mailing list and me will be making tests this Thursday. He's helping me to install Rust and, if needed, we'll have a remote session so I can also help with tests. If you want, please wait until we finish those tests. Thanks.

**Comment by pablgonz** [comment]
@nvdaes Hola, veo que tú estas a cargo de la traducción al español, muchas gracias por tu trabajo, he publicado un petición en (https://github.com/daisy/MathCAT/issues/579) y claro @NSoiffer  no habla español así que puede que parezca un poco extraña...Soy profesor de matemáticas de primaria/secundaria (Chile) y usuario de LaTeX desde hace mucho, me interesa el tema del etiquetado PDF y por eso está la petición.

Si puedo colaborar con algo solo hazme un ping y responderé lo más pronto posible.
Saludos 

PD: Sé que es una cuenta genérica, pero puedes encontrar mi correo en el paquete `enumext` o `scontents` de LaTeX en CTAN...gracias por la colaboración.

**Comment by NSoiffer** [comment]
@pablgonz

Sorry about my reply not being in Spanish....

There are several things you can do to help out.
1. Fix any speech you think is poor
2. Update the Spanish version to the latest rules in the English branch (this will pick up the current support for `intent`).
3. Write more tests for the Spanish version -- it only has a few which means that changes I make to MathCAT in general might break some Spanish speech and I won't know that.

There is [an updated translator guide here](https://daisy.github.io/MathCAT/new_translators_guide_MathCAT_revised) which is helpful if you want to address #1 or # 3.

There is also a tool to help spot what needs updating. @MartheGjelstad has volunteered to help translators with that tool and other translation issues.  Please reach out to her if you want to tackle # 2.

**Comment by nvdaes** [comment]
@pablgonz sorry for my late reply.
I'm happy with your willness to collaborate.
If there's something I can do, please let me know.

"Disculpas por la demora en mi respuesta. Me alegro de que quieras colaborar. Si hay algo que yo pueda hacer, por favor házmelo saber".
Noelia (Spain).

**Comment by pablgonz** [comment]
@NSoiffer  Thanks for replying.
@nvdaes (Noelia) Thank you so much for taking the time to reply. I'd like to collaborate, but I need more interaction with Spanish-speaking users who are interested in this. Could you update your fork (https://github.com/nvdaes/MathCAT) and allow "issues" and "discussions"?

In about a month, I'll have a macro package just for writing valid math for MathCat with output in Spanish (we have our own rules).

@nvdaes (Noelia)  Muchas gracias por tomarte el tiempo en responder...me gustaría colaborar pero necesito más interacción con usurios de habla hispana que esten interesados en esto, ¿puedes actualizar tu fork (https://github.com/nvdaes/MathCAT) y permitir "issues" y "discusiones"?

En un mes más menos tendré un macro paquete solo para escribir matemática valida para mathcat y con salida en contexto español (nosotros tenemos nuestras propias reglas).

**Comment by nvdaes** [comment]
@pablgonz I'll update my fork. But I'm not sure about maintaining discussions there. Perhaps this is a good idea, but I'd like to explore other possibilities, for example the creation of a mailing list to facilitate discussions even from people who is not using GitHub.
I don't discard your idea. Is just that I would like to think in a wider range of possibilities.
Also, I think that forks should be used carefully to avoid confusions. My forks are used to contribute upstreams repositories. Of course sometimes forks can work independently for a valid reason. I'll think on this.
What I would like to have are spanish books properly writen in MathML
For me, studying math in recorded audio was painful, and I cjan even remember that a human reader said that he would skip tables, and I understand it.
I think that braille and navigation is essential, so let me know if there's something I can do.

Actualizaré mi bifurcación, pero quiero pensar en la mejor forma de comunicación para tratar el tema de matemáticas en español. Puede que tu idea sea buena, pero me gustaría considerar posibilidades como crear una lista de correo para que gente que no usa GitHub pueda participar. Además, no me gustaría causar confusiones al usar mi bifurcación de forma inapropiada.
Me gustaría disponer de algún libro de matemáticas en español escrito con MathML.
Tengo un mal recuerdo al haber estudiado matemáticas grabadas en audio, y un lector incluso dijo que se saltaría unas tablas, y lo entiendo. Creo que el braille y la navegación son esenciales, así que intentaré ayudar si hay algo que yo pueda hacer.

**Comment by pablgonz** [comment]
@nvdaes Muchas gracias por tomar en consideración la idea :D una lista de correo sería genial, pero es poco funcional para algunas cosas, lo de dejar tu repo abierto para issues y discusiones lo miré desde la perspectiva colaborativa LaTeX, no para discutir como tal, sino cual es la mejor manera de ... y lo de issues es directamente por que lee (o entiende) mathcat en español (algunas cosas no suenan muy bien por ejemplo los logaritmos).

Al día de hoy dudo que exista un texto en español escrito con MathML, pero gracias al avance del proyecto de etiquetado del equipo LaTeX ahora si se pueden lograr muchas cosas y es lo recomendado en [Best Practice Guide: Math in PDF](https://pdfa.org/resource/best-practice-guide-math-in-pdf/). De momento estoy trabajando en un paquete para poder escribir las cosas usuales (escolares) con las que trabajo, por ejemplo puedo escribir $$1,2\overline{34}$$ y que mathcat (v0.7.6-beta.3 y la instalada por defecto en NVDA) lo entienda como:

```xml
<math xmlns="http://www.w3.org/1998/Math/MathML">
 <mn>1</mn>
 <mrow intent="coma">
 <mi mathvariant="normal">​</mi>
 <mo lspace="0" rspace="0">,</mo>
 </mrow>
 <mn>2</mn>
 <mi intent="con" mathvariant="normal">​</mi>
 <mover intent="periodico:postfix($n)">
 <mn arg="n">
 34
 </mn>
 <mo>‾</mo>
 </mover>
</math>
```
Y lo lea como "1 coma 2 con 34 periodico" que es la lectura correcta en Chile/Argentina/México (y más). Quedo atento a cualquier novedad.

(inglés) Thank you so much for considering the idea :D A mailing list would be great, but it's not very practical for some things. I considered leaving your repo open for issues and discussions from a LaTeX collaborative perspective, not for discussion per se, but rather to determine the best way to... and the issue section is directly because it reads (or understands) MathCat in Spanish (some things don't sound quite right, for example, logarithms).

As of today, I doubt there's a Spanish text written with MathML, but thanks to the progress of the LaTeX team's tagging project, many things are now possible, and it's recommended in [Best Practice Guide: Math in PDF](https://pdfa.org/resource/best-practice-guide-math-in-pdf/). I'm currently working on a package to write the usual (school-related) things I work with. For example, I can write $$1,2\overline{34}$$ and have Mathcat (v0.7.6-beta.3, the default version installed in NVDA) interpret it as:

```xml
<math xmlns="http://www.w3.org/1998/Math/MathML">
 <mn>1</mn>
 <mrow intent="coma">
 <mi mathvariant="normal">​</mi>
 <mo lspace="0" rspace="0">,</mo>
 </mrow>
 <mn>2</mn>
 <mi intent="con" mathvariant="normal">​</mi>
 <mover intent="periodico:postfix($n)">
 <mn arg="n">
 34
 </mn>
 <mo>‾</mo>
 </mover>
</math>
```
And read it as "1 coma 2 con 34 periodico" which is the correct reading in Chile, Argentina, México (and more). I'll be waiting for any updates.

@NSoiffer My apologies for using this space to communicate, but it's for a good cause...and thank you very much for the MathCAT Demo (it's the only way to work from Linux and see how things turn out).

**Comment by nvdaes** [comment]
Me gustaría conocer la opinión de @NSoiffer 
Tal vez sea mejor que él habilite las discusiones de GitHub para debatir sobre distintos idiomas en su repositorio, ya que él es quien lo mantiene.
Yo he colaborado con la traducción, pero tú también vas a colaborar. Entonces, ¿qué criterio seguimos para elegir el repositorio que podemos usar para debatir? Puede ser el mío, pero también el tuyo o el de cualquier otro traductor.
Sin embargo, cualquier persona estará de acuerdo en que quien mantiene MathCAT es @NSoiffer 

I'd like to know @NSoiffer opinion on this matter. Perhaps he can enable GitHub Discussions to discuss about translations, for example using categories for different languages.
Otherwise, how to choose the appropriate repo to discuss for each language? Any repo of a translator may be used. But everybody will agree on the fact that @NSoiffer is the maintainer.

**Pull request merged**
